#type: UNet
_target_: models.ConvNeXtUNet #models.UNet
name: test_01
c_in: ${data.context_size} # input channels == number of input frames
c_out: 1 # output channels == number of output frames
c_list: [32, 64, 128] # TODO: Adjust this
spatial_factor_list: [2, 2] # TODO: Adjust this
num_block_list: [5, 5] # TODO: Adjust this
